# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "recording-server",
    "recording-analyzer",
    "shared",
]
